# umbrella values for the safezone project
global:
  environment: "preview" # REQUIRED: Environment name (e.g., dev, preview, staging, production)
  ghcr:
    imagePullSecret: ghcr-pull-secret
  database:
    existingSecret: safezone-role-password
  redis:
    host: valkey-state.safezone-preview.svc.cluster.local
    existingSecret: k3han-redis-secrets
  cache:
    host: valkey-cache.safezone-preview.svc.cluster.local
    port: 6379
    existingSecret: safezone-cache-secrets
  kafka:
    brokers: k3han-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    topic: "preview.covid.case.data"
    consumerGroup: "safezone-worker-group"

# readPipeline subchart contains the analytics API and dashboard
readPipeline:
  analyticsAPI:
    tag: 0.3.7-168eb6e
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values: 
                 - always

# writePipeline subchart contains the simulator、ingestor and worker
writePipeline:
  simulator:
    tag: 0.3.7-168eb6e
    volume:
      persistentVolumeClaim:
        type: "smoke-test"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values: 
                 - always
  ingestor:
    tag: 0.3.7-168eb6e
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values: 
                 - always
  worker:
    tag: 0.3.7-168eb6e
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values: 
                - always