apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: safezone-preview-foundation
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: safezone
  source:
    repoURL: https://github.com/SafeChord/SafeZone-Deploy.git
    targetRevision: preview/0.3.7
    path: helm-charts/safezone-foundation
    helm:
      releaseName: safezone-foundation
      valueFiles:
        - values-preview.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: safezone-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Ignore metadata changes to avoid unnecessary syncs
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: safezone-cli-relay
    jsonPointers:
    - /metadata/app