apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: safezone-staging-ui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: safezone
  source:
    repoURL: https://github.com/SafeChord/SafeZone-Deploy.git
    targetRevision: staging
    path: helm-charts/safezone-ui
    helm:
      releaseName: safezone-ui
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: safezone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true