apiVersion: v2
name: safezone-foundation
description: Umbrella chart for SafeZone project at phase foundation (routing, config, support services)
type: application
version: 0.3.7
appVersion: 0.3.7

dependencies:
- name: safezone-common
  version: 0.3.7
  repository: "file://../safezone-common"
- name: cliRelay
  version: 0.3.7
  repository: "file://charts/cliRelay"
- name: timeServer
  version: 0.3.7
  repository: "file://charts/timeServer"