global:
  environment: preview # REQUIRED: Environment name (e.g., dev, preview, staging, production)
  ghcr:
    imagePullSecrets: ghcr-pull-secret 
  database:
    existingSecret: safezone-role-password
  redis:
    host: valkey-state.safezone-preview.svc.cluster.local
    existingSecret: k3han-redis-secrets
  cache:
    host: valkey-cache.safezone-preview.svc.cluster.local
    port: 6379
    existingSecret: safezone-cache-secrets

cliRelay:
  image:
    tag: 0.3.7-168eb6e
  auth:
    roleFile: /app/roles.yml
    authSecret: safezone-auth-secrets
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always

timeServer:
  image:
    tag: 0.3.7-168eb6e
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/avail
                operator: In
                values:
                  - always

cache:
  auth:
    existingSecret: safezone-cache-secrets
    ## @param auth.existingSecretPasswordKey Password key to be retrieved from existing secret
    ## NOTE: ignored unless `auth.existingSecret` parameter is set

  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: chorde.io/avail
                  operator: In
                  values:
                    - always

route:
  host: preview-safezone.omh.idv.tw