apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: safezone-preview-infra-stage
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: foundation
            path: deploy/preview/infra/foundation
            wave: "-2"
          - stage: security
            path: deploy/preview/infra/security
            wave: "1"
          - stage: workloads
            path: deploy/preview/infra/workloads
            wave: "2"
          - stage: init
            path: deploy/preview/infra/init
            wave: "3"
  template:
    metadata:
      name: 'preview-infra-{{stage}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        safezone.io/stage: preview-infra
        safezone.io/component: '{{stage}}'
    spec:
      project: safezone
      source:
        repoURL: https://github.com/SafeChord/SafeZone-Deploy.git
        targetRevision: preview/0.3.7
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
