apiVersion: v2
name: cliRelay
description: SafeZone CLI Relay Service
type: application
version: 0.3.7
appVersion: 0.3.7

dependencies:
- name: safezone-common
  version: 0.3.7
  repository: "file://../../../safezone-common"