apiVersion: v2
name: safezone-ops
description: Chart for operational Jobs (seed, smoke, scheduled routines) in SafeZone project
type: application
version: 0.3.7
appVersion: "0.3.7"

dependencies:
- name: safezone-common
  version: 0.3.7
  repository: "file://../safezone-common"
