image:
  pullSecret: ghcr-pull-secret
  tag: 0.3.7-168eb6e

auth:
  authSecret: safezone-auth-secrets

env:
  environment: "preview"
  relayTimeout: 5400 # set a longer timeout for seeding job

job:
  name: "safezone-ops-cases"
  command: [bash, /app/routines/preview/seed_data.sh]
